[package]
name = "udpmultiplexer"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1"
clap = { version = "4.2.1", features = ["derive"] }
